[build]
builder = "nixpacks"

[[services]]
name = "server"
path = "server"
start_command = "yarn dev"
healthcheck_path = "/health"
healthcheck_timeout = 100
port = 8080
env = { PORT = "8080" }

[[services]]
name = "client"
path = "client"
start_command = "yarn dev"
port = 3000
env = { PORT = "3000" }

[[services]]
name = "worker"
path = "worker"
start_command = "go run src/main.go"
