services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached # Match devcontainer.json's workspaceFolder
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    build:
      context: ../database
      dockerfile: mysql.Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: