services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached # Match devcontainer.json's workspaceFolder
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis  # Add redis as a dependency

  mysql:
    build:
      context: ../database
      dockerfile: mysql.Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest  # Use the official Redis image
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - redis_data:/data  # Persist Redis data across container restarts

volumes:
  mysql_data:
  redis_data:  # Define a volume for Redis data persistence
